//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrorLogReader {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    public sealed partial class ErrorLogReader : global::System.Configuration.ApplicationSettingsBase {
        
        private static ErrorLogReader defaultInstance = ((ErrorLogReader)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ErrorLogReader())));
        
        public static ErrorLogReader Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=FundingApplicationWafDatabase;Integrated Security=T" +
            "rue;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationInt" +
            "ent=ReadWrite;MultiSubnetFailover=False")]
        public string ConectionString {
            get {
                return ((string)(this["ConectionString"]));
            }
        }
    }
}
